---
- name: Registry create
  hosts: registry
  gather_facts: false
  tasks:
  - name: Apt install docker registry
    apt:
      name: docker-registry
      state: present
    become: true
    
- name: Ensure docker
  hosts: devservers
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - ikabds
